import Link from 'next/link'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { NavBar } from './components/NavBar'


export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>InventApp</title>
      </head>
      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
